version: '3.8'
services:
  frontend:
    container_name: nextjs-app
    build: ./my-app
    # image: testdockera/nextjs-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
      - mongodb

  backend:
    container_name: node-eggjs-backend
    build: ./backend
    # image: testdockera/nextjs-backend
    ports:
      - "7001:7001"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DB_HOST=mongodb
    depends_on:
      - mongodb
    volumes:
      - ./backend:/usr/src/app

  mongodb:
    container_name: mongodb
    image: mongo:4.4
    ports:
      - "27017:27017"
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongodb-data:/data/db
  
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

volumes:
  mongodb-data:
    driver: local
