# 使用官方Node.js镜像作为基础镜像
FROM node:20

# 设置工作目录
WORKDIR /usr/src/backend

# 将 package.json 和 package-lock.json 复制到工作目录
COPY package*.json ./

# 安装项目依赖
RUN npm install

# 复制后端项目文件到工作目录
COPY . .

# 开放端口
EXPOSE 7001

# 运行Egg.js服务
CMD ["npm", "start"]
